// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WPFScholifyApp.DAL.ClassRepository;

#nullable disable

namespace WPFScholifyApp.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassTeacher", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("integer");

                    b.Property<int>("TeachersId")
                        .HasColumnType("integer");

                    b.HasKey("ClassesId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("ClassTeacher");
                });

            modelBuilder.Entity("ParentsPupil", b =>
                {
                    b.Property<int>("ParentsId")
                        .HasColumnType("integer");

                    b.Property<int>("PupilsId")
                        .HasColumnType("integer");

                    b.HasKey("ParentsId", "PupilsId");

                    b.HasIndex("PupilsId");

                    b.ToTable("ParentsPupil");
                });

            modelBuilder.Entity("ScheduleSubject", b =>
                {
                    b.Property<int>("SchedulesId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("integer");

                    b.HasKey("SchedulesId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("ScheduleSubject");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Admin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.DayBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attendance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("DayBooks");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Parents", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Pupil", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Pupils");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("Timeslot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClassTeacher", b =>
                {
                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParentsPupil", b =>
                {
                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Parents", null)
                        .WithMany()
                        .HasForeignKey("ParentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Pupil", null)
                        .WithMany()
                        .HasForeignKey("PupilsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScheduleSubject", b =>
                {
                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Schedule", null)
                        .WithMany()
                        .HasForeignKey("SchedulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Admin", b =>
                {
                    b.HasOne("WPFScholifyApp.DAL.DBClasses.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("WPFScholifyApp.DAL.DBClasses.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.DayBook", b =>
                {
                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Class", "Class")
                        .WithMany("DayBooks")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Subject", "Subject")
                        .WithMany("DayBooks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Teacher", "Teacher")
                        .WithMany("DayBooks")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Parents", b =>
                {
                    b.HasOne("WPFScholifyApp.DAL.DBClasses.User", "User")
                        .WithOne("Parents")
                        .HasForeignKey("WPFScholifyApp.DAL.DBClasses.Parents", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Pupil", b =>
                {
                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Class", "Class")
                        .WithMany("Pupils")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFScholifyApp.DAL.DBClasses.User", "User")
                        .WithOne("Pupil")
                        .HasForeignKey("WPFScholifyApp.DAL.DBClasses.Pupil", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Schedule", b =>
                {
                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Class", "Class")
                        .WithOne("Schedule")
                        .HasForeignKey("WPFScholifyApp.DAL.DBClasses.Schedule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Teacher", b =>
                {
                    b.HasOne("WPFScholifyApp.DAL.DBClasses.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("WPFScholifyApp.DAL.DBClasses.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPFScholifyApp.DAL.DBClasses.Subject", "Subject")
                        .WithMany("Teachers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Class", b =>
                {
                    b.Navigation("DayBooks");

                    b.Navigation("Pupils");

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Subject", b =>
                {
                    b.Navigation("DayBooks");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.Teacher", b =>
                {
                    b.Navigation("DayBooks");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("WPFScholifyApp.DAL.DBClasses.User", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Parents")
                        .IsRequired();

                    b.Navigation("Pupil")
                        .IsRequired();

                    b.Navigation("Teacher")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
